version: "2"

services:
  app:
    build:
      context: .
      dockerfile: app_dockerfile
    volumes:
      - ./..:/home/ruby
    ports:
        - "3000:3000"
    links:
      - db
    tty: true

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=ruby
      - MYSQL_USER=ruby
      - MYSQL_PASSWORD=GdS)FP6*B7zJ
      - MYSQL_ROOT_PASSWORD=yQqDx.4(Cnue
